services:
  wallet-db:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=wallet_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5431:5432'

  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - '6379:6379'